title: GLORB User Guide
description: User resources for the GLORB smart lamp
theme: jekyll-theme-cayman
# baseurl: "/GLORB-User-Guide"  # Removed for custom domain

# Navigation
header_pages:
  - index.md
  - setup.md
  - firmware.md
  - releases.md
  - troubleshooting.md